FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=yourpassword
ENV WEBHOOK_URL=https://your-subdomain.up.railway.app
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=8080

EXPOSE 8080

CMD ["n8n"]
